### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by abhi150** [BhargavaRavaliKoganti/Online_Auction_System_Project#2]
how to install the supporting files ,
how to run the file
It shows error like No MySQLdb

**Comment by BhargavaRavaliKoganti** [comment]
Go through Django frame work. Until and unless you are familiar with it you cannot run and understand. 
No MySQLdb means you haven't created a MySQL database in your local machine.

**Comment by abhi150** [comment]
Can you please give me your mobile number ?
So that i can contact for further deatils

**Comment by BhargavaRavaliKoganti** [comment]
You can raise out the issues over hear.
